# Generated by Django 5.1.3 on 2025-02-11 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement_type', models.CharField(choices=[('upload', 'Upload Images'), ('kinect', 'Use Kinect Data'), ('manual', 'Input Measurements')], default='manual', max_length=10)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('image1_data', models.BinaryField(blank=True, null=True)),
                ('image2_data', models.BinaryField(blank=True, null=True)),
                ('chest_girth', models.FloatField(blank=True, null=True)),
                ('hips_girth', models.FloatField(blank=True, null=True)),
                ('waist_girth', models.FloatField(blank=True, null=True)),
                ('thigh_girth', models.FloatField(blank=True, null=True)),
                ('neck_size', models.FloatField(blank=True, null=True)),
                ('upper_arm_girth', models.FloatField(blank=True, null=True)),
                ('calves_girth', models.FloatField(blank=True, null=True)),
                ('upper_arm_length', models.FloatField(blank=True, null=True)),
                ('lower_arm_length', models.FloatField(blank=True, null=True)),
                ('upper_leg_length', models.FloatField(blank=True, null=True)),
                ('lower_leg_length', models.FloatField(blank=True, null=True)),
                ('torso_length', models.FloatField(blank=True, null=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
