# Generated by Django 5.1.3 on 2025-02-09 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_measurement_kinect_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='data',
            field=models.JSONField(default=dict),
        ),
    ]
