# Generated by Django 5.1.3 on 2025-02-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_measurement_image1_alter_measurement_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
    ]
